                                                                                                                                                      # This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Upload CrystalPol to PyPI

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:

  pypi-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        python -m poetry install
    - name: Test with unittest
      run: |
        python -m poetry run python -m unittest -v
    - name: Upload Pip Package
      run: |
        python -m poetry config repositories.pypi https://pypi.org/legacy/
        python -m poetry publish --build --username __token__ --password ${{secrets.PYPI_TOKEN}} --repository pypi